name: ai_camera
description: "A Flutter AI Camera App powered by Gemini API created by Chandresh"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_generative_ai: ^0.4.0
  camera: ^0.10.5+5
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
